### ISSUE TITLE
4.6.1 not able to replace node 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#10337]
replace falls with 

```
storage_service - replace[7b2becdd-7917-4c17-8eb6-a0db06c2c8ee]: Failed to send heartbeat: std::runtime_error (node_ops_cmd_check: Node 192.168.41.225 rejected node_ops_cmd=8 from node=192.168.41.225 with ops_uuid=7b2becdd-7917-4c17-8eb6-a0db06c2c8ee, pending_node_ops={}, the node ops is unknown)
```

scylla.yaml

```
cluster_name: *** Cluster
num_tokens: 256
data_file_directories:
     - /var/lib/cassandra/data/vol
commitlog_directory: /var/lib/cassandra/commitlog
saved_caches_directory: /var/lib/cassandra/saved_caches
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
                    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
                              - seeds:  "audiencedb001.spotx.den01.pop,audiencedb004.spotx.den01.pop,audiencedb007.spotx.den01.pop"
listen_address:  192.168.41.225
broadcast_address: 192.168.41.225
listen_on_broadcast_address: false
native_transport_port: 9042
native_shard_aware_transport_port: 19042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
cas_contention_timeout_in_ms: 1000
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address:  192.168.41.225
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 64
authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer
initial_token:
broadcast_rpc_address: 192.168.41.225
hints_directory: /var/lib/cassandra/hints
view_hints_directory: /var/lib/cassandra/view_hints
hinted_handoff_enabled: true
max_hint_window_in_ms: 10800000 
permissions_validity_in_ms: 300000
permissions_update_interval_in_ms: 100000
permissions_cache_max_entries: 10000
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb:  635625
storage_port: 7000
ssl_storage_port: 7001
start_native_transport: true
start_rpc: false
incremental_backups: false
snapshot_before_compaction: false
auto_snapshot: false
tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000
murmur3_partitioner_ignore_msb_bits: 12
replace_address: 192.168.41.225
enable_repair_based_node_ops: false
failure_detector_timeout_in_ms: 1200000
```

```
Datacenter: realtime
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  192.168.42.136  1.83 TB    256          ?       be8748be-69be-4ca2-9ed2-319b0c0f2222  rack1
UN  192.168.42.137  1.81 TB    256          ?       9ea4a90b-432a-447a-8e7d-d7641dedd4bb  rack1
UN  192.168.42.138  1.83 TB    256          ?       2541ead4-da71-4c4c-848f-d759e49faf8a  rack1
UN  192.168.42.139  1.8 TB     256          ?       0c1143ff-4367-48c9-9fe2-802d1f4c8a10  rack1
UN  192.168.42.140  1.87 TB    256          ?       59073f2b-d9a0-44fa-ae80-93e9695a1783  rack1
UN  192.168.42.141  1.91 TB    256          ?       021556b1-5d32-4dd7-857a-0e98e8678184  rack1
UN  192.168.42.142  1.93 TB    256          ?       40d3c919-cfb3-4f5f-8e82-31bc7bbe8bf4  rack1
UN  192.168.42.143  1.95 TB    256          ?       abb8cb4c-4386-493d-b1a8-7196dbd37dad  rack1
UN  192.168.42.128  1.96 TB    256          ?       52f4b176-5b07-42e7-86f2-9f9ffeb93fa3  rack1
UN  192.168.42.129  1.84 TB    256          ?       e39f14db-afa3-4b49-9a5f-020950a736bf  rack1
UN  192.168.42.130  1.87 TB    256          ?       dd0b738d-2f8e-4a4d-9ca5-0b8450dff445  rack1
UN  192.168.42.131  1.72 TB    256          ?       916aa22f-a394-4f84-8acb-ffaa0d321309  rack1
UN  192.168.42.133  1.86 TB    256          ?       b1bd9f6d-b932-49cb-ae54-9f725ada2705  rack1
UN  192.168.42.134  1.88 TB    256          ?       0806a400-93a4-4a79-b6c6-20d3ebb61f8e  rack1
UN  192.168.42.135  1.85 TB    256          ?       346633c9-af91-46c1-9f20-8f08fd7cf502  rack1
UN  192.168.42.144  1.9 TB     256          ?       10413591-232f-4388-99c4-d15443d0c15c  rack1
UN  192.168.42.145  1.83 TB    256          ?       eea0661f-25d2-4cd9-a7e2-0b5dda5e1e4a  rack1
UN  192.168.42.146  1.85 TB    256          ?       b873fa4d-8469-49bc-9b51-c1c775b80aa2  rack1
UN  192.168.42.147  1.85 TB    256          ?       fee46e85-5586-48c0-9ea4-65e1480d7ecd  rack1
UN  192.168.42.148  1.86 TB    256          ?       c104e310-3d3a-456b-8ba1-6a0e7152629f  rack1
UN  192.168.42.149  1.8 TB     256          ?       a8af8c58-6cb2-4918-8978-087a588c2c86  rack1
UN  192.168.42.150  1.81 TB    256          ?       28038226-3fdc-4597-a5ed-058e6df66bbf  rack1
UN  192.168.42.151  1.78 TB    256          ?       33768cdc-8208-4351-ab9f-eaea4507e3ee  rack1
UN  192.168.41.232  1.84 TB    256          ?       c29114ab-782f-433d-877e-7ecba979c1ad  rack1
UN  192.168.41.233  1.9 TB     256          ?       ffa53dfd-f848-45af-ab6a-45e236d372e5  rack1
UN  192.168.41.234  1.93 TB    256          ?       c411b4b8-5eb3-4ca1-9932-e78304a65bb7  rack1
UN  192.168.41.235  1.84 TB    256          ?       bf1b0eea-9a1f-4108-82e8-e829c2569f38  rack1
DN  192.168.41.225  1.87 TB    256          ?       2a10d145-569c-4a37-b5ff-a6cc1ea177d7  rack1
UN  192.168.41.226  1.91 TB    256          ?       67a2b3cd-a71d-4bb4-9e0b-478c60c9f206  rack1
UN  192.168.41.228  1.81 TB    256          ?       02f7bcdb-f5f2-45e8-b9fe-e67c163cfbe8  rack1
UN  192.168.41.229  1.8 TB     256          ?       d8ee34e3-6aa7-4837-b6ae-2103c130ce99  rack1
UN  192.168.41.230  1.74 TB    256          ?       b4d79371-aa1b-4a4d-86c6-84a8c23a1434  rack1
UN  192.168.42.120  1.82 TB    256          ?       3191e1a6-5b93-454e-bbc7-cb35af77bf48  rack1
UN  192.168.42.121  1.91 TB    256          ?       c8ba37cd-1ad1-449d-8970-985d22ee1890  rack1
UN  192.168.42.122  1.84 TB    256          ?       fd0e86c0-810e-4d3c-9561-5ae212327905  rack1
UN  192.168.42.123  1.85 TB    256          ?       288c915f-3d00-49d7-a10b-b1da15a54304  rack1
UN  192.168.42.124  1.79 TB    256          ?       a88c32df-5369-40ea-8474-81937e795dde  rack1
UN  192.168.42.125  1.9 TB     256          ?       34ee4b71-8401-4efc-86b4-e8f33ef07224  rack1
UN  192.168.42.126  1.9 TB     256          ?       bac85a18-fd00-4b22-a7d0-d9899e2d894d  rack1
UN  192.168.42.127  1.99 TB    256          ?       c0e25f76-f9d9-4947-a59e-1a6f02101345  rack1
UN  192.168.42.116  1.8 TB     256          ?       7a684440-6022-4ca3-a4be-2a3651d5384f  rack1
UN  192.168.42.117  1.84 TB    256          ?       bbcc910a-e205-41bb-adff-df88c388d95a  rack1
UN  192.168.42.118  1.82 TB    256          ?       e4dc86d2-5cbc-42dc-bb59-6bf53c27d67f  rack1
UN  192.168.42.119  1.81 TB    256          ?       0158341c-6548-4bc9-a307-e30e04cab117  rack1
UN  192.168.41.201  1.91 TB    256          ?       ec2ecbe5-9378-4c96-9807-74276fe9fb0a  rack1
UN  192.168.41.202  1.91 TB    256          ?       956fa92f-f4f6-4e55-98b3-b237b31204ae  rack1
UN  192.168.41.203  1.84 TB    256          ?       48d13090-1164-492e-80e7-1046d5727545  rack1
UN  192.168.41.204  1.86 TB    256          ?       55c4c5d3-5959-4890-8d3d-10440d34c857  rack1
UN  192.168.41.206  1.87 TB    256          ?       a81882e3-3cf1-4c91-8201-f976edaef68d  rack1
UN  192.168.41.207  1.73 TB    256          ?       6a7cd283-0673-43fa-bb0f-c6a74b2dd3a7  rack1
UN  192.168.41.196  1.72 TB    256          ?       47184799-d324-43ad-a3ce-936f790e2f94  rack1
UN  192.168.41.198  1.85 TB    256          ?       12715393-dd60-4e68-9357-56e2d7ab6e02  rack1
UN  192.168.41.199  1.84 TB    256          ?       79fc455a-5628-4b8e-a4d7-b11485f4a2b4  rack1
```

scylla is started with
```
/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --lock-memory 1 --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-15,17-31
```
