### ISSUE TITLE
Cluster start stucked on first node where seed is only node itself

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#10355]
Scylla version: Scylla version 5.1.dev-0.20220401.af0751992861 with build-id 6cdf33534b4e6cb7e6d0388411c310957961e94a 
Dtest to reproduce: materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_test

Cluster with raft feature initialization stucked on first node even with correct sequence of cluster configuration with ccmlib:

1. cluster.set_configuration
2. cluster.populate(>2)
3. cluster.start

Test `materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_test` was patched with valid steps.
First node has seed only itself:
```
experimental_features:
- raft

seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 127.0.25.1
```
Other nodes have seeds all previous node and itself. 

 But cluster initialization is stucked on first node.
db log is attached
[system.log](https://github.com/scylladb/scylla/files/8465236/system.log)

Steps to rerpoduce:
1. get test from https://github.com/scylladb/scylla-dtest/pull/2694
2.  `pytest -vvv -s -p "no:email_plugin" --keep-test-dir --scylla-version=unstable/master:latest materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_test`
Actual results:
test failed. Node is not started
