### ISSUE TITLE
hostname: Name or service not known

### ISSUE THREAD

**Issue by nexcode** [scylladb/scylladb#12011]
*Installation details:*
Scylla version (or git commit hash): 5.0.5
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 9

*compose.yaml:*
```
version: "2.4"
services:
  service:
    image: scylladb/scylla:5.0.5
    container_name: scylla
    command:
      - --options-file=/opt/share/scylla.yaml
      - --workdir=/opt/workdir
      - --listen-address=192.168.0.1 # affects /etc/scylla.d/docker.conf
      - --seeds=192.168.0.1,192.168.0.2,192.168.0.3 # affects /etc/scylla.d/docker.conf
      - --developer-mode=0
    network_mode: host
    restart: on-failure
    volumes:
      - /opt/dsp-scylla-main/share:/opt/share:ro
      - /opt/dsp-scylla-main/workdir:/opt/workdir:rw
```

*autogenerated /etc/scylla.d/docker.conf:*
```
SCYLLA_DOCKER_ARGS="--overprovisioned --listen-address "192.168.0.1" --rpc-address "192.168.0.1" --seed-provider-parameters seeds="192.168.0.1,192.168.0.2,192.168.0.3" --alternator-address "192.168.0.1" --blocked-reactor-notify-ms 999999999 --options-file=/opt/share/scylla.yaml --workdir=/opt/workdir"
```

**ERROR:**
```
scylla | hostname: Name or service not known
scylla | failed!
scylla | Traceback (most recent call last):
scylla |   File "/docker-entrypoint.py", line 28, in <module>
scylla |     setup.cqlshrc()
scylla |   File "/scyllasetup.py", line 71, in cqlshrc
scylla |     hostname = subprocess.check_output(['hostname', '-i']).decode('ascii').strip()
scylla |   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 424, in check_output
scylla |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
scylla |   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
scylla |     raise CalledProcessError(retcode, process.args,
scylla | subprocess.CalledProcessError: Command '['hostname', '-i']' returned non-zero exit status 1.
```

Why need `hostname -i` if all listen adresses are provided?

**Comment by nexcode** [comment]
The problem is in scyllasetup.py file:
```
    def cqlshrc(self):
        home = os.environ['HOME']
        hostname = subprocess.check_output(['hostname', '-i']).decode('ascii').strip()
        with open("%s/.cqlshrc" % home, "w") as cqlshrc:
            cqlshrc.write("[connection]\nhostname = %s\n" % hostname)
```

We temporarily fixed it by reassembling the image:
```
FROM scylladb/scylla:5.0.5
RUN sed -i "s|\['hostname', '-i'\]|\['echo', '127.0.0.1'\]|g" /scyllasetup.py
```

**Comment by avikivity** [comment]
Looks like we need to install hostname. But maybe we can use a python function instead, to avoid an extra useless package.

**Comment by nexcode** [comment]
It will be more correct this way:
```
FROM scylladb/scylla:5.0.5
RUN sed -i "s|\['hostname', '-i'\]|\['hostname', '-I'\]|g" /scyllasetup.py
```

**Comment by mykaul** [comment]
> > Looks like we need to install hostname. But maybe we can use a python function instead, to avoid an extra useless package.
> 
> hostname installed and available. He doesn't know the `-i` argument, but he knows `-I`. Apparently, this is a mistake of the developers.

Those are not the same. Mine (Fedora 37) knows both:
```
[ykaul@ykaul scylla-enterprise]$ hostname -i
fe80::ceb3:9bfb:83d1:1683%wlp0s20f3 10.100.102.15
[ykaul@ykaul scylla-enterprise]$ man hostname
[ykaul@ykaul scylla-enterprise]$ hostname -I
10.100.102.15
```

'man' says:
```
     -i, --ip-address
              Display the network address(es) of the host name. Note that this works only if the host name can be resolved. Avoid using this option; use hostname --all-ip-addresses instead.

       -I, --all-ip-addresses
              Display all network addresses of the host. This option enumerates all configured addresses on all network interfaces. The loopback interface and IPv6 link-local addresses are omitted. Contrary to option -i, this option does not depend on name resolution. Do not make any assumptions about the or‐
              der of the output.

```

**Comment by mykaul** [comment]
@yaronkaikov - I think your team should look at this, if we can either do it in Python, or install hostname (and hope it's new enough to understand '-i' !)

**Comment by syuu1228** [comment]
I think I found out why this happens, it is because hostname resolution doesn't working when `network_mode: host`.
When we don't specify network_mode (I think default mode is bridge) or when we specify `network_mode: bridge`, it just work fine.
To fix the problem, we need to manually add hostname entry to /etc/hosts using `extra_hosts`, like this:
```
version: "2.4"
services:
  service:
    image: scylladb/scylla:5.0.5
    container_name: scylla
    hostname: scylla-host
    command:
      - --options-file=/opt/share/scylla.yaml
      - --workdir=/opt/workdir
      - --listen-address=192.168.0.1 # affects /etc/scylla.d/docker.conf
      - --seeds=192.168.0.1,192.168.0.2,192.168.0.3 # affects /etc/scylla.d/docker.conf
      - --developer-mode=0
    network_mode: host
    restart: on-failure
    volumes:
      - /opt/dsp-scylla-main/share:/opt/share:ro
      - /opt/dsp-scylla-main/workdir:/opt/workdir:rw
    extra_hosts:
      - "scylla-host:192.168.0.1"
```
After added /etc/hosts `hostname: Name or service not known` does not occur on host mode.
