### ISSUE TITLE
RFE: Support encrypted metrics endpoint

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylladb#12302]
#### Reasoning

Currently, ScyllaDB supports exposing prometheus metrics via unencrypted endpoint.  
This has two major security issues:
* Anyone can access them and extract potentially sensitive metadata information - cluster topology, keyspace/table names 
* There's no safe way to remotely pull metrics without additional layer

To protect potentially sensitive information from leaking and allow to build centralized monitoring, the traffic to the metrics endpoint should be protected by mTLS.

#### Requirements
* User can disable the unencrypted metrics endpoint via configuration file - already implemented
* User can enable encrypted metrics endpoint via configuration file
* User can configure server key, certificate and trusted client CA of metrics endpoint via configuration file
* Serving certificate is dynamically reloaded upon change - CQL already supports it, it should be the same here

#### API proposal

Current prometheus configuration options shall be extended with simillar to `client_encryption_options` used for CQL mTLS, allowing to set up a serving certificate, and client certification validation. 
For example:
```
prometheus_port_ssl: 9181
prometheus_encryption_options:
  require_client_auth: true
  certificate: "/serving-certs/tls.crt"
  keyfile: "/serving-certs/tls.key"
  truststore: "/client-ca/tls.crt"
```
