### ISSUE TITLE
Failed to start a 3 node cluster with 5.2.0-rc2 and docker compose

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13145]
Scylla version (or git commit hash): 5.2.0-rc2
Cluster size: 3 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

docker-compose.yml
```
version: "3"

services:

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.2.0-rc2
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/mutant-data.txt:/mutant-data.txt"
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:5.2.0-rc2
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:5.2.0-rc2
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

networks:
  web:
    driver: bridge

```
(from https://github.com/scylladb/scylla-code-samples/tree/master/mms)

```
> docker-compose up -d
Creating scylla-node3 ... 
Creating scylla-node2 ... 
Creating scylla-node1 ... 
...
```

Error I got 
```
ERROR 2023-03-12 14:53:25,569 [shard 0] init - Startup failed: std::runtime_error (Node 172.19.0.3 has gossip status=UNKNOWN. Try fixing it before adding new node to the cluster.)
2023-03-12 14:53:25,600 INFO exited: scylla (exit status 1; not expected)
2023-03-12 14:53:26,600 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

The error is **inconsistent**, in some cases cluster init was completed successfully
