### ISSUE TITLE
cannot see the 2nd scylladb node instance using docker tutorial

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/scylladb#14784]
latest scylladb tutorial as attached, cant see the 2nd node.

anyone tried before? ubuntu 22.04
![Screenshot from 2023-07-21 09-19-39](https://github.com/scylladb/scylladb/assets/51492452/563d652a-0ed4-4af9-a168-e46d3bbd5c81)

**Comment by hiqsociety** [comment]
wait a long time, still same

**Comment by hiqsociety** [comment]
tried docker compose style is the same
```
version: '3'

services:
  some-scylla:
    image: scylladb/scylla
    container_name: some-scylla

  some-scylla2:
    image: scylladb/scylla
    container_name: some-scylla2
    command: --seeds=some-scylla

  some-scylla3:
    image: scylladb/scylla
    container_name: some-scylla3
    command: --seeds=some-scylla
~                                     
```
