### ISSUE TITLE
Error in seed address lookup causes initialization of an already bootstrapped node to fail

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylladb#14945]
Currently, ScyllaDB performs an eager lookup of provided seeds on initialisation: https://github.com/scylladb/scylladb/blob/39ca07c49b257d37856164ea5b845f7b98224b98/init.cc#L35.

An error in address lookup will hence cause ScyllaDB process to fail initialization. This is expected during bootstrap.

However, this is also going to cause an already bootstrapped node to fail after it has been restarted, e.g.:
```
ERROR 2023-08-03 08:35:54,663 [shard 0] init - Bad configuration: invalid value in 'seeds': 'dummy.scylla.svc.cluster.local': std::system_error (error C-Ares:4, dummy.scylla.svc.cluster.local: Not found)
```

According to the [documentation](https://opensource.docs.scylladb.com/stable/kb/seed-nodes.html): "**Once the nodes have joined the cluster, seed node has no function**".
I believe that an error in seed lookup should not cause an already bootstrapped node to fail during initialization. 
If needed, it should only be performed lazily for bootstrapped nodes.

cc @zimnx 

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2.0
Cluster size: n/a
OS (RHEL/CentOS/Ubuntu/AWS AMI): n/a

**Comment by DoronArazii** [comment]
@kostja please take a look

**Comment by DoronArazii** [comment]
> @kostja please take a look

@kostja ping

**Comment by mykaul** [comment]
@kostja ?

**Comment by mykaul** [comment]
@kostja - please assign to a team member to look at this.

**Comment by kostja** [comment]
@rzetelskik please provide:
- your configuration file
- a motivation for the change, other than "the documentation says". 

The reason I am asking is that this issue can be addressed both by changing the code and changing the documentation.  And it is not obvious why changing the code is the best way to proceed.

First of all, the peers may be needed again when you recover from a degraded state, i.e. in recovery mode. In this case you re-assemble the cluster from disjoint nodes. So the docs are not correct saying that peers are never needed again.

Second, until a node looks up the existing cluster, it is not obvious whether or not it might or might not need seeds. The cluster assembly is based on host ids, and seeds list IP addresses. IP addresses of existing hosts may change, and in this case seeds are used to discover existing nodes.  Again, it may sound like an incompleteness of our docs, sigh, but either way, I don't think it's the best idea to boot a node which configuration file is incorrect.

**Comment by kbr-scylla** [comment]
> First of all, the peers may be needed again when you recover from a degraded state, i.e. in recovery mode. In this case you re-assemble the cluster from disjoint nodes. So the docs are not correct saying that peers are never needed again.

The docs are saying that about seeds, not peers.

**Comment by rzetelskik** [comment]
> a motivation for the change, other than "the documentation says"

I believe I've already put it in the original comment: "this is also going to cause an already bootstrapped node to fail after it has been restarted"

Say, for example, that you add a datacenter to an existing cluster using a domain name resolving to one of the nodes of the existing DCs as the initial seed. The DC comes up and joins the cluster. After a while the name used as the initial seed is no longer resolvable. If you restart any of the nodes which used the name as the initial seed, they won't start due to the above error, even though you haven't changed the configuration and all of their peers are UN. Would you say the node being restarted is misconfigured in that case?

> So the docs are not correct saying that seeds are never needed again.

Agreed, I suppose the docs can also be corrected then. The issue is not that the docs state the seeds are no longer used past bootstrap, and they are, but that looking the seed up in this situation breaks the node, even though doing so is not strictly necessary.

**Comment by rzetelskik** [comment]
I've tried my best to abstract away from what we do in kube to prepare the config and scenario to reproduce it.
We'll create a cluster composed of two DCs, where the second one uses a DNS name resolving to the first node of the first DC as the initial seed.

scylla.yaml, common for all the nodes:
```
api_address: 127.0.0.1
api_doc_dir: /opt/scylladb/api/api-doc/
api_port: 10000
api_ui_dir: /opt/scylladb/swagger-ui/dist/
batch_size_fail_threshold_in_kb: 1024
batch_size_warn_threshold_in_kb: 128
cas_contention_timeout_in_ms: 1000
client_encryption_options:
  certificate: /var/run/secrets/scylla-operator.scylladb.com/scylladb/serving-certs/tls.crt
  enabled: true
  keyfile: /var/run/secrets/scylla-operator.scylladb.com/scylladb/serving-certs/tls.key
  optional: false
  require_client_auth: true
  truststore: /var/run/secrets/scylla-operator.scylladb.com/scylladb/client-ca/tls.crt
cluster_name: simple-cluster
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
consistent_cluster_management: true
endpoint_snitch: GossipingPropertyFileSnitch
force_schema_commit_log: true
listen_address: localhost
murmur3_partitioner_ignore_msb_bits: 12
native_shard_aware_transport_port: 19042
native_transport_port: 9042
native_transport_port_ssl: 9142
num_tokens: 256
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
read_request_timeout_in_ms: 5000
rpc_address: 0.0.0.0
rpc_port: 9160
schema_commitlog_segment_size_in_mb: 32
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 127.0.0.1
write_request_timeout_in_ms: 2000
```

The first DC, us-east-1, with one rack us-east-1a of 3 nodes, has the following overridden for its nodes:
us-east-1a-0 (10.0.0.131):
```
/docker-entrypoint.py --smp=1 --prometheus-address=0.0.0.0 --broadcast-address=10.0.0.131 --broadcast-rpc-address=10.0.0.131 --listen-address=0.0.0.0 --seeds=10.0.0.131 --developer-mode=1 --overprovisioned=1
```

us-east-1a-1 (10.0.0.96):
```
/docker-entrypoint.py --developer-mode=1 --overprovisioned=1 --smp=1 --prometheus-address=0.0.0.0 --broadcast-address=10.0.0.96 --broadcast-rpc-address=10.0.0.96 --listen-address=0.0.0.0 --seeds=10.0.0.131
```

us-east-1a-2 (10.0.0.17):
```
/docker-entrypoint.py --overprovisioned=1 --smp=1 --prometheus-address=0.0.0.0 --broadcast-address=10.0.0.117 --broadcast-rpc-address=10.0.0.117 --listen-address=0.0.0.0 --seeds=10.0.0.131 --developer-mode=1
```

When the first DC is UN, to reproduce, add `10.0.0.131 dummy.scylla.svc.cluster.local` to `/etc/hosts` on all of the hosts of the nodes of the other DC, us-east-2, composed of a single rack us-east-2a of 3 nodes. The nodes override config with the following:

us-east-2a-0 (10.0.0.221):
```
/docker-entrypoint.py --developer-mode=1 --overprovisioned=1 --smp=1 --prometheus-address=0.0.0.0 --broadcast-address=10.0.0.221 --broadcast-rpc-address=10.0.0.221 --listen-address=0.0.0.0 --seeds=dummy.scylla.svc.cluster.local
```

us-east-2a-1 (10.0.0.227):
```
/docker-entrypoint.py --listen-address=0.0.0.0 --seeds=dummy.scylla.svc.cluster.local,10.0.0.221 --developer-mode=1 --overprovisioned=1 --smp=1 --prometheus-address=0.0.0.0 --broadcast-address=10.0.0.227 --broadcast-rpc-address=10.0.0.227
```

us-east-2a-2 (10.0.0.207):
```
/docker-entrypoint.py --developer-mode=1 --overprovisioned=1 --smp=1 --prometheus-address=0.0.0.0 --broadcast-address=10.0.0.207 --broadcast-rpc-address=10.0.0.207 --listen-address=0.0.0.0 --seeds=dummy.scylla.svc.cluster.local,10.0.0.221
```

Now, when the clusters is up and running, remove the earlier added entry from `/etc/hosts` from the last node of the second DC (us-east-2a-2) and restart Scylla. It's going to fail with with the following:
```
ERROR 2023-10-03 19:37:10,250 [shard 0] init - Bad configuration: invalid value in 'seeds': 'dummy.scylla.svc.cluster.local': std::system_error (error C-Ares:4, dummy.scylla.svc.cluster.local: Not found)
...
ERROR 2023-10-03 19:37:13,620 [shard 0] init - Startup failed: bad_configuration_error (std::exception)
2023-10-03 19:37:13,667 INFO exited: scylla (exit status 1; not expected)
2023-10-03 19:37:14,669 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

Even though its peers, including the initial seeds, are UN:
```
Datacenter: us-east-1
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.0.0.131   280 KB     256          ?       97a830bd-9ebf-447c-9aba-1d576c2d4c82  us-east-1a
UN  10.0.0.96  728 KB     256          ?       d1ae7b31-3092-49b4-b491-e60a9ed37e3d  us-east-1a
UN  10.0.0.17  688 KB     256          ?       13fe20f3-09b1-4b32-8312-3434fa450a42  us-east-1a
Datacenter: us-east-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.0.0.227  928 KB     256          ?       d2e38937-5eab-4dfd-ac7e-d7ab8c0abc84  us-east-2a
DN  10.0.0.207  1.36 MB    256          ?       a939f193-51ae-4a1f-adec-3ef4f3f825d4  us-east-2a
UN  10.0.0.221  900 KB     256          ?       a188b693-b8e3-454f-a332-75e4f4d64e21  us-east-2a
```

This setup can obviously be simplified, but I stuck with how we initially hit it (although with a DNS server).

As we discussed privately @kostja, this doesn't involve modifying the config, and basically comes down to ignoring the DNS resolution errors past bootstrap. Let me know what you think and if this information is sufficient.
