### ISSUE TITLE
CQL: fetch TLS config: get SSL user cert from secrets store: not found

### ISSUE THREAD

**Issue by firegrouptech** [scylladb/scylladb#16995]
Hello everyone,

I encountered an issue after installing the Scylla Operator 1.11.1 chart version. I used the default values for both scylla-operator and scylla-manager. For ScyllaDB, I configured the following settings:

```
developerMode: true
cpuset: false
hostNetworking: true
automaticOrphanedNodeCleanup: true
datacenter: "k3s"
# List of racks
racks:
  - name: "local"
    # Name of additional scylla config configMap
    scyllaConfig: "scylla-config"
    # Name of additional scylla manager agent config stored as secret
    scyllaAgentConfig: "scylla-agent-config"
    # Number of rack members (nodes)
    members: 3
    # Storage definition
    storage:
      capacity: 10Gi
    # Scylla container resource definition
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
```
The deployment was successful. However, when I executed the command sctool status -c scylla/scylla inside the scylla-manager pod, I encountered an error, as shown in the image below.
![image](https://github.com/scylladb/scylladb/assets/156646587/c3ecb584-7565-428e-bf35-92f74ec6433a)
Is it a normal error ? 
Does it have any effect?
If effect, how can i fix it ?
Is there any way to disable TLS Config and use it without TLS
