### ISSUE TITLE
 ScyllaDB node isn't connected to a node in another cluster

### ISSUE THREAD

**Issue by ku9nov** [scylladb/scylladb#17228]
I have multi-datacenter clusters in different regions and VPCs. They have node-to-node access by service names, configured by Istio.

<details>
  <summary>Manifest of the first cluster</summary>

```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 5.4.0
  agentVersion: 3.2.5
  developerMode: true
  cpuset: true
  sysctls:
  - "fs.aio-max-nr=2097152"
  automaticOrphanedNodeCleanup: true
  exposeOptions:
    broadcastOptions:
      clients:
        type: ServiceClusterIP
      nodes:
        type: ServiceClusterIP
    nodeService:
      type: ClusterIP
  datacenter:
    name: sfo3
    racks:
    - name: a
      members: 1
      storage:
        storageClassName: do-block-storage
        capacity: 15Gi
      agentResources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
```
</details>

<details>
  <summary>Manifest of the second cluster</summary>

```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 5.4.0
  agentVersion: 3.2.5
  developerMode: true
  cpuset: true
  sysctls:
  - "fs.aio-max-nr=2097152"
  automaticOrphanedNodeCleanup: true
  exposeOptions:
    broadcastOptions:
      clients:
        type: ServiceClusterIP
      nodes:
        type: ServiceClusterIP
    nodeService:
      type: ClusterIP
  externalSeeds:
  - scylla-cluster-sfo3-a-0
  datacenter:
    name: fra1
    racks:
    - name: a
      members: 1
      storage:
        storageClassName: do-block-storage
        capacity: 15Gi
      agentResources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
```
</details>

<details>
  <summary>Nodetool status output from both clusters</summary>

First(sfo3):

```
kubectl -n=scylla exec -it pod/scylla-cluster-sfo3-a-0 -c=scylla -- nodetool status
Datacenter: fra1
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UJ  10.245.54.15    ?          256          ?       null                                  a
Datacenter: sfo3
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  10.245.106.147  6.8 MB     256          ?       02f5cbee-5936-4658-89d6-3124688a2ba7  a

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

Second(fra1):

```
kubectl -n=scylla exec -it pod/scylla-cluster-fra1-a-0 -c=scylla -- nodetool status
Datacenter: fra1
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UJ  10.245.54.15    0 bytes    256          ?       null                                  a
Datacenter: sfo3
================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  10.245.106.147  ?          256          ?       02f5cbee-5936-4658-89d6-3124688a2ba7  a

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

</details>

I don't understand what is wrong now, node in fra1 just stuck in joining state. Let me know if I can provide some additional information.

I used this [tutorial](https://operator.docs.scylladb.com/stable/multidc/multidc.html).

*Installation details*
Scylla version (or git commit hash): 5.4.0
Kubernetes in Digital Ocean
