### ISSUE TITLE
std::system_error table - failed to write sstable after running with docker-compose

### ISSUE THREAD

**Issue by IamMusavaRibica** [scylladb/scylladb#17363]
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.1.7 from docker, 65cebc139ce3
Cluster size:
OS: Windows 10

I've tried to set up scylla db using Docker Desktop. Here is the relevant part of docker-compose:

```yaml
  scylla:
    image: "scylladb/scylla:5.1.7"
    command: "--smp 1 --skip-wait-for-gossip-to-settle 0 --developer-mode 1"
    ports:
      - "9042:9042"
    volumes:
      - "./tools/scylla:/var/lib/scylla"
    healthcheck:
      test: cqlsh -e "exit"
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s
```
After running `docker-compose up`, scylla doesn't run and instead spams these errors in a potentially infinite loop: 
```
...
scylla-1    | INFO  2024-02-15 11:43:00,688 [shard 0] compaction_manager - Starting off-strategy compaction for system.schema_functions, 0 candidates were found
scylla-1    | INFO  2024-02-15 11:43:00,688 [shard 0] compaction_manager - Done with off-strategy compaction for system.schema_functions
scylla-1    | INFO  2024-02-15 11:43:00,689 [shard 0] sstable_directory - Removing file /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-1-big-TOC.txt.tmp
scylla-1    | INFO  2024-02-15 11:43:00,691 [shard 0] seastar - updated: blocked-reactor-notify-ms=999999999
scylla-1    | INFO  2024-02-15 11:43:00,691 [shard 0] init - starting storage proxy
scylla-1    | INFO  2024-02-15 11:43:00,691 [shard 0] compaction_manager - Starting off-strategy compaction for system.local, 0 candidates were found
scylla-1    | INFO  2024-02-15 11:43:00,693 [shard 0] compaction_manager - Done with off-strategy compaction for system.local
scylla-1    | INFO  2024-02-15 11:43:00,693 [shard 0] init - starting forward service
scylla-1    | INFO  2024-02-15 11:43:00,693 [shard 0] init - starting migration manager
scylla-1    | INFO  2024-02-15 11:43:00,693 [shard 0] init - starting query processor
scylla-1    | INFO  2024-02-15 11:43:00,694 [shard 0] init - initializing batchlog manager
scylla-1    | INFO  2024-02-15 11:43:00,694 [shard 0] system_keyspace - Setting local host id to b49acfcb-104e-4e36-ab25-94555ea96f29
scylla-1    | ERROR 2024-02-15 11:43:00,706 [shard 0] table - failed to write sstable /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-1-big-Data.db: std::system_error (No such file or directory)
scylla-1    | ERROR 2024-02-15 11:43:00,706 [shard 0] table - Memtable flush failed due to: std::system_error (error system:2, No such file or directory). Aborting, at 0x50d5c6e 0x50d6160 0x50d6468 0x1363a75 0x4d4b634 0x4d4ca17 0x4d4bc6c 0x4cf1ba8 0x4cf1081 0x10344f6 0x1031ada /opt/scylladb/libreloc/libc.so.6+0x27b74 0x10309ad
```
After leaving my pc running for a few hours, I came back to a full ssd, all files in the commitlog folder, most of them consisting mostly of null bytes. I have expected to be able to run scylla db normally, because I haven't done any changes in the configuration or anything. 

![image](https://github.com/scylladb/scylladb/assets/65848142/bfd47971-862c-4258-8b7e-9d10e62ea35d)

![image](https://github.com/scylladb/scylladb/assets/65848142/19fc5f86-c9cd-482b-b684-84ddf5ab86b3)
