### ISSUE TITLE
scylla_io_setup poor write performance in mdadm volume

### ISSUE THREAD

**Issue by owanio1992** [scylladb/scylladb#18579]
*describe*
after exec scylla_io_setup
mdadm volume write performance become very low 
1113.37 MiB/s ->  201 MiB/s

*Installation details*
Scylla version: 5.1.19
Cluster size: 1
OS: Ubuntu server 22.04

*Hardware details *
aws ec2 d3.4xlarge  12 x 2TB HDD
manual config mdadm raid 5 with 12 disk
mount in  /mnt_data

os use gp3:
  throughput: 125 MB/s
  IOPS: 3000

*scylla.yaml config*
```
data_file_directories:
   - /mnt_data
```

reproduction

delete io_properties.yaml
```
sudo rm -f /etc/scylla.d/io_properties.yaml
sudo reboot 
```

test sequential write bandwidth
```
TEST_DIR=/mnt_data/fiotest
sudo rm -rf ${TEST_DIR} && sudo mkdir -p ${TEST_DIR}

BS=8M
rw=write
sudo fio --directory=${TEST_DIR} --size=10G --direct=1 --rw=${rw} --randrepeat=0 \
--ioengine=libaio --bs=${BS} \
--iodepth=8 --time_based=1 --runtime=180 --name=fio_${write}_${BS}
```

result avg bandwidth 1113.37 MiB/s
```
   bw (  MiB/s): min=  352, max= 1552, per=100.00%, avg=1113.37, stdev=195.28, samples=359
   iops        : min=   44, max=  194, avg=139.08, stdev=24.37, samples=359
```

exec 
```
sudo scylla_io_setup
```

result of io_properties.yaml
```
disks:
  - mountpoint: /
    read_iops: 2999
    read_bandwidth: 131302008
    write_iops: 3238
    write_bandwidth: 132983320
  - mountpoint: /mnt_data
    read_iops: 2479
    read_bandwidth: 2092237312
    write_iops: 808
    write_bandwidth: 134219856
```

do fio test again, the ave bandwidth become very low ~ 201 MiB/s
```
   bw (  KiB/s): min=16384, max=311919, per=100.00%, avg=201621.15, stdev=47872.88, samples=351
   iops        : min=    2, max=   38, avg=24.60, stdev= 5.84, samples=351
```

then reboot 
do fio test again, the ave bandwidth become normal  1124 MiB/s
```
   bw (  MiB/s): min=  240, max= 1490, per=100.00%, avg=1124.70, stdev=200.48, samples=359
   iops        : min=   30, max=  186, avg=140.51, stdev=25.02, samples=359
```
