### ISSUE TITLE
[Doc] Change the Log Level in scylla.yaml

### ISSUE THREAD

**Issue by temichus** [scylladb/scylladb#19463]
Scylla documentation has information on how to change the Log Level here https://opensource.docs.scylladb.com/stable/troubleshooting/log-level.html#how-to-change-log-level-offline

but it describes only how to change the level via SCYLLA_ARGS(CMD) and no information how to change it in scylla.yaml.
[scylla.yaml](https://github.com/scylladb/scylladb/blob/master/conf/scylla.yaml) also doet not mention **default_log_level** and 
**logger_log_level** parameters.

example how they can be used in scylla.yaml
```
default_log_level: error
logger_log_level: 
  sstable: debug
  cql_server: trace
```
