### ISSUE TITLE
docs: Certificate-based Authentication is not clear enougth

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#19608]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-6.0/operating-scylla/security/certificate-authentication

### Problem
It is not clear how Certificate-based Authentication is mapped to [RBAC](https://opensource.docs.scylladb.com/stable/operating-scylla/security/rbac-usecase.html) Roles / Users.

### Suggest a fix
Info from [@elcallio](https://github.com/elcallio)

Authentication maps to a role, not necessarily a role, with LOGIN = true, also known as Users.
The certificate is verified against the transport CA, which in turn can have a certficate_revocation_list (CRL), referenced from scylla.yaml (attribute of client_encryption_options).
Admin can remove/disable a user using the CRL.
Example:
```
With the following config
      auth_certificate_role_queries:
               - source: SUBJECT
                 query: CN=([^,\s]+)
```

And a certificate subject of
`Subject has: CN=Mark, OU=Developers, O=Mycompany C=UK`

Scylla will try to match **Mark** to a role.
