### ISSUE TITLE
system.config has a strange value for a 'seed_provider' key

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#21269]
HEAD: 298cafff3537950f1b17b1fcf119e3d831bcd786

## Description

`system.config` has the following strange "seed_provider_type" value:

```
cqlsh> SELECT * from system.config where name='seed_provider';

 name          | source | type          | value
---------------+--------+---------------+----------------------
 seed_provider | config | seed provider | "seed_provider_type"

(1 rows)
```

While the corresponding scylla.yaml content is:

```
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "10.0.2.4"
```

And hence the expected value in `system.config` is:

```
[
        { 
          "class_name": "org.apache.cassandra.locator.SimpleSeedProvider",
          "parameters": [
            { 
              "seeds": "10.0.2.4"
            }
          ]
        }
]
```
