### ISSUE TITLE
scylla.config: incorrect format of storring of 'client_encryption_options.enabled'

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#21355]
HEAD: 298cafff3537950f1b17b1fcf119e3d831bcd786

## Description

The boolean value is not supposed to be quoted in JSON:

scylla.yaml:
```
client_encryption_options:
    enabled: true
    certificate: /etc/scylla/secret_certificate.crt
    keyfile: /etc/scylla/secret_keyfile.pem
    truststore: /etc/scylla/secret_truststore.crt
```

```
scylla_admin@cqlsh> SELECT * from system.config where name='client_encryption_options';

 name                      | source | type       | value
---------------------------+--------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 client_encryption_options | config | string map | {"truststore":"/etc/scylla/secret_truststore.crt","keyfile":"/etc/scylla/secret_keyfile.pem","certificate":"/etc/scylla/secret_certificate.crt","enabled":"true"}

(1 rows)
```
