### ISSUE TITLE
Add REST API for exposing backup endpoints

### ISSUE THREAD

**Issue by robertbindar** [scylladb/scylladb#22428]
Currently there are multiple places where one can configure the object storage endpoints
increasing the chance of misconfigurations.
Scylla needs to become the source of truth so we need to add an API which will provide the list
of available endpoints.
Deliverables:
* API that gets the list of available endpoints
* API that provides the default endpoint (or at least we should get a good understanding of how the current default is determined by Rclone)
* Backup/restore validates that passed endpoint belongs to the list of available endpoints.
* File followup for making SM-Agent get the endpoint from the new API

**Comment by Michal-Leszczynski** [comment]
In terms of the information needed by SM, it would be good to get all of the configured  information (apart from secrets):
```yaml
endpoints:
  - name: s3.us-east-2.amazonaws.com
    port: 443
    https: true
    aws_region: us-east-2
    aws_access_key_id: EXAMPLE_ACCESS_KEY_ID # <- secret
    aws_secret_access_key: EXAMPLE_SECRET_ACCESS_KEY # <- secret
```
Moreover, it would also be good to get the information about the provider.
Right now the only supported one would be `s3`, but in the future the list might be extended with `gcs` and `azure`.

**Comment by robertbindar** [comment]
@Michal-Leszczynski thanks for the clarification! Making all the info available sounds good to me.

The issue with add `provider`  is that there is no current standardization for the `object_storage.yaml` file.
For instance, the current parsing of the config looks for `aws_region` option and if that's present, it means it's an S3 endpoint so it starts looking for other tokens as well (like secret and id), otherwise it just leaves it populated with only the endpoint URL and port.
In my case for the API,  for now I can just hardcode provider to "S3" and later when we add more providers, we can either
a) do the same as the parsing code does, i.e. look for a token specific to a provider and deduce the provider (this comes with a risk of creating a config soup)
b) enforce explicitly specifying the provider via a new config option
c) standardize the file with new sections for providers, e.g.
```
endpoints:
  - s3
    - name: s3.us-east-2.amazonaws.com
      port: 80
      https: false
      aws_region: us-east-2
    - name: s3provider2
  - gcs
    - name: some_provider1
    ...
    - name: some_provider2
```
Any thoughts on a) b) c) ?
