### ISSUE TITLE
Increase systemd coredump generation timeout

### ISSUE THREAD

**Issue by glommer** [scylladb/scylladb#5430]
Today we saw a user environment in which coredumps were not being generated.

Upon investigation, the user discovered that this was because systemd was timing out the process.
We managed to generate a coredump once they tweaked the following property:

```
/lib/systemd/system/systemd-coredump@.service:
RuntimeMaxSec
```

We already override some of those properties related to size in our default packaging. We should override that too.

In big machines with a lot of data and not necessarily a fast disk, coredump generation can take a long time.

**Comment by dorlaor** [comment]
@penberg can you give this a try? It's been pending for so long and it's a tiny change, a customer pointed it to me

**Comment by dorlaor** [comment]
Probably a RuntimeMaxSec=1h is a decent long enough time for this

**Comment by vladzcloudius** [comment]
@avikivity @mykaul @dorlaor @DoronArazii Guys, we are hitting this badly!
(This issue is from 2019!)

**Comment by vladzcloudius** [comment]
@d-helios @tarzanek FYI

**Comment by vladzcloudius** [comment]
The playbook used to work this around was:

```
---
- name: configure core dump
  gather_facts: no
  hosts: node
  tasks:
    - name: create directory
      file:
        path: "/etc/systemd/system/systemd-coredump@.service.d"
        state: directory
      become: yes

    - name: create override file for systemd-coredump
      copy:
        dest: "/etc/systemd/system/systemd-coredump@.service.d/override.conf"
        content: |
         [Service]
          RuntimeMaxSec=
          TimeoutSec=
          RuntimeMaxSec=4h
          TimeoutSec=4h

        owner: root
      become: yes


    - name: reload systemd
      systemd:
        daemon-reload: yes
      become: yes
```
