### ISSUE TITLE
node to node encryption non-ssl port issue 

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylladb#7500]
@vladzcloudius @tzach @eliransin @slivne 

Scylla Version 2019.1.11

customer is enabling node to node encryption: 
```
# storage_port: 7000
ssl_storage_port: 7001
#native_transport_port: 9042
native_transport_port_ssl: 9142

client_encryption_options:
    enabled: true
    certificate: /etc/scylla/keys/db.crt
    keyfile: /etc/scylla/keys/db.key
    require_client_auth: True
    truststore: /etc/scylla/keys/cadb.pem
server_encryption_options:
    internode_encryption: all
    certificate: /etc/scylla/keys/db.crt
    keyfile: /etc/scylla/keys/db.key
    truststore:  /etc/scylla/keys/cadb.pem
```
encryption/SSL is working.

Scylla still listening on port 7000 and 9042 not encrypted (example of 9042/9142:

```
INFO  2020-10-29 02:12:21,257 [shard 0] storage_service - Starting listening for CQL clients on [fcff:1:172:92::226]:9042 (unencrypted)
INFO  2020-10-29 02:12:21,857 [shard 0] storage_service - Starting listening for CQL clients on [fcff:1:172:92::226]:9142 (encrypted)
```
If setting  ` storage_port: 0 ` and ` ssl_storage_port: 7001`  Scylla listening only on ssl port 7001.
If setting  `native_transport_port: 9142 `  then it come up as encrypted. 

Expected behaviour would be that is encryption + ssl port  enable - scylla will listen only on ssl ports.
