### ISSUE TITLE
Set the right default snitch: Ec2MultiRegion for AWS

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#9386]
When installing Scylla on AWS, the [default snitch should be Ec2MultiRegion](https://docs.scylladb.com/operating-scylla/procedures/cluster-management/ec2-dc/). 
googlecloudsnitch for GCP.

**Comment by slivne** [comment]
https://github.com/scylladb/scylla-machine-image/issues/221

**Comment by avikivity** [comment]
Doesn't this cause compatibility problems if a user adds an instance from a new AMI to a cluster that was started using an old AMI? The node would not connect.

**Comment by mykaul** [comment]
@yaronkaikov - what's the next step here?

**Comment by syuu1228** [comment]
We haven't merged the PRs we will have compatibility issue with existing AMIs once we switched to Ec2MultiRegionSnitch as @avikivity commented above, how about to let users to manually specify Ec2MultiRegionSnitch via user-data like this:
```
scylla_yaml:
  cluster_name: test-cluster
  experimental: true
  endpoint_snitch: Ec2MultiRegionSnitch
  seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
        - seeds: 10.0.219.209
```
And then we need a patch to apply public IP for broadcast_address, broadcast_rpc_address and seeds, just like we did on https://github.com/scylladb/scylla-machine-image/pull/278.


Or, we may implement it in opposite way - Ec2MultiRegionSnitch by default and user can revert it to Ec2Snitch via user-data, but still can cause problem on user side, since default configuration refuses to connect existing (old) AMI instances.
